"""01_initial-db

Revision ID: 149d6f3209ad
Revises: 
Create Date: 2022-11-17 21:04:54.007280

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '149d6f3209ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
