"""01_initial-db

Revision ID: 8a283eb8b758
Revises: b4b68812d8ac
Create Date: 2022-11-17 21:16:04.418577

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8a283eb8b758'
down_revision = 'b4b68812d8ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column(
        'is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('links_activity', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links_activity', sa.Column(
        'is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('links', 'is_deleted')
    # ### end Alembic commands ###
