"""01_initial-db

Revision ID: 96102d72f72f
Revises: 
Create Date: 2022-11-19 15:36:30.303724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96102d72f72f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_link', sa.String(length=2083), nullable=False),
    sa.Column('short_link', sa.String(length=8), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.DateTime(), nullable=True),
    sa.Column('client', sa.String(length=20), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links_activity')
    op.drop_table('links')
    # ### end Alembic commands ###
