"""01_initial-db

Revision ID: b4b68812d8ac
Revises: 149d6f3209ad
Create Date: 2022-11-17 21:11:23.498833

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b4b68812d8ac'
down_revision = '149d6f3209ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_link', sa.String(length=2083), nullable=False),
    sa.Column('short_link', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.DateTime(), nullable=True),
    sa.Column('client', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links_activity')
    op.drop_table('links')
    # ### end Alembic commands ###
